# Generated by Django 4.2.8 on 2024-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('User_Name', models.CharField(max_length=30)),
                ('Pass_Word', models.CharField(max_length=30)),
                ('Mobile_No', models.CharField(max_length=30)),
                ('Mail_Id', models.CharField(max_length=30)),
                ('Locality', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
    ]
